### ISSUE TITLE
OSError: libopencv_imgcodecs.so.3.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Santhosh1509** [AastaNV/JEP#17]
Installed OpenCV using https://github.com/AastaNV/JEP/blob/master/script/install_opencv4.0.0_Nano.sh

installed mxnet 
https://drive.google.com/file/d/1jr-kP1_zlLa9tx-GtdlBV3Nn20qRJgzY/view

As suggested https://devtalk.nvidia.com/default/topic/1049293/jetson-nano/i-was-unable-to-compile-and-install-mxnet-on-the-jetson-nano-is-there-an-official-installation-tutorial-/?#id="comment_5326170"

I am getting this error 

> Traceback (most recent call last):
>   File "myscript.py", line 5, in <module>
>     from core.symbol import P_Net, R_Net, O_Net
>   File "/home/user/Documents/distanc/core/symbol.py", line 1, in <module>
>     import mxnet as mx
>   File "/home/user/.virtualenvs/test/lib/python3.6/site-packages/mxnet/__init__.py", line 24, in <module>
>     from .context import Context, current_context, cpu, gpu, cpu_pinned
>   File "/home/user/.virtualenvs/test/lib/python3.6/site-packages/mxnet/context.py", line 24, in <module>
>     from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
>   File "/home/user/.virtualenvs/test/lib/python3.6/site-packages/mxnet/base.py", line 213, in <module>
>     _LIB = _load_lib()
>   File "/home/user/.virtualenvs/test/lib/python3.6/site-packages/mxnet/base.py", line 204, in _load_lib
>     lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
>   File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: libopencv_imgcodecs.so.3.3: cannot open shared object file: No such file or directory

Tried this https://github.com/cggos/dip_cvqt/issues/1#issuecomment-284103343

on trying this 

`sudo find / -name "libopencv_imgcodecs.so.3.3"`

Can not find any such file

Saw 

https://stackoverflow.com/questions/43152412/libopencv-imgcodecs-so-3-2-cannot-open-shared-object-file-no-such-file-or-dire

https://answers.opencv.org/question/6732/missing-shared-library/

Ran this

```
sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf' 
sudo ldconfig
```

Still i am getting the same error

Please guide, confused here

**Comment by Santhosh1509** [comment]
Ran this

`sudo find / -name "libopencv_imgcodecs.so*"`

got this 

> /home/rlpl123/opencv/opencv-4.0.0/release/lib/libopencv_imgcodecs.so.4.0.0
> /home/rlpl123/opencv/opencv-4.0.0/release/lib/libopencv_imgcodecs.so
> /home/rlpl123/opencv/opencv-4.0.0/release/lib/libopencv_imgcodecs.so.4.0
> /usr/lib/aarch64-linux-gnu/libopencv_imgcodecs.so.3.2.0
> /usr/lib/aarch64-linux-gnu/libopencv_imgcodecs.so
> /usr/lib/aarch64-linux-gnu/libopencv_imgcodecs.so.3.2
> /usr/local/lib/libopencv_imgcodecs.so.4.0.0
> /usr/local/lib/libopencv_imgcodecs.so
> /usr/local/lib/libopencv_imgcodecs.so.4.0

from where do i make mxnet point from `libopencv_imgcodecs.so.3.3` to `libopencv_imgcodecs.so.4.0`
to avoid

> Traceback (most recent call last):
> File "myscript.py", line 5, in 
> from core.symbol import P_Net, R_Net, O_Net
> File "/home/user/Documents/distanc/core/symbol.py", line 1, in 
> import mxnet as mx
> File "/home/user/.virtualenvs/test/lib/python3.6/site-packages/mxnet/init.py", line 24, in 
> from .context import Context, current_context, cpu, gpu, cpu_pinned
> File "/home/user/.virtualenvs/test/lib/python3.6/site-packages/mxnet/context.py", line 24, in 
> from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
> File "/home/user/.virtualenvs/test/lib/python3.6/site-packages/mxnet/base.py", line 213, in 
> _LIB = _load_lib()
> File "/home/user/.virtualenvs/test/lib/python3.6/site-packages/mxnet/base.py", line 204, in _load_lib
> lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
> File "/usr/lib/python3.6/ctypes/init.py", line 348, in init
> self._handle = _dlopen(self._name, mode)
> OSError: libopencv_imgcodecs.so.3.3: cannot open shared object file: No such file or directory

How to 😕❓
